from django.core.management.base import BaseCommand, CommandError
from django.utils import timezone

from medicine.constants import DEFAULT_MEDICINE_STATUS
from medicine.repository import MedicineRepository


MEDICINES = [
    {
        "medicine_code": "MED001",
        "name": "Paracetamol 500mg",
        "generic_name": "Paracetamol",
        "dosage_form": "Tablet",
        "strength": "500mg",
        "category": "Pain reliever",
        "manufacturer": "DHG Pharma",
        "batch_number": "BATCH001",
        "manufacture_date": "2026-01-15",
        "expiration_date": "2028-01-15",
        "description": "Common pain reliever and fever reducer.",
        "location": "Warehouse A",
        "temperature": 25.5,
        "humidity": 60,
        "storage_condition": "Store below 30C",
        "quality_status": "Passed",
    },
    {
        "medicine_code": "MED002",
        "name": "Amoxicillin 500mg",
        "generic_name": "Amoxicillin",
        "dosage_form": "Capsule",
        "strength": "500mg",
        "category": "Antibiotic",
        "manufacturer": "Imexpharm",
        "batch_number": "BATCH002",
        "manufacture_date": "2026-02-10",
        "expiration_date": "2028-02-10",
        "description": "Antibiotic for bacterial infection treatment.",
        "location": "Warehouse B",
        "temperature": 24.0,
        "humidity": 58,
        "storage_condition": "Store below 30C",
        "quality_status": "Passed",
    },
    {
        "medicine_code": "MED003",
        "name": "Vitamin C 1000mg",
        "generic_name": "Ascorbic Acid",
        "dosage_form": "Effervescent Tablet",
        "strength": "1000mg",
        "category": "Vitamin",
        "manufacturer": "OPC Pharma",
        "batch_number": "BATCH003",
        "manufacture_date": "2026-03-05",
        "expiration_date": "2027-03-05",
        "description": "Vitamin C supplement for immune support.",
        "location": "Warehouse C",
        "temperature": 25.0,
        "humidity": 55,
        "storage_condition": "Keep in dry place",
        "quality_status": "Passed",
    },
    {
        "medicine_code": "MED004",
        "name": "Cetirizine 10mg",
        "generic_name": "Cetirizine",
        "dosage_form": "Tablet",
        "strength": "10mg",
        "category": "Antihistamine",
        "manufacturer": "Stella Pharm",
        "batch_number": "BATCH004",
        "manufacture_date": "2026-04-12",
        "expiration_date": "2028-04-12",
        "description": "Medicine for allergy symptom relief.",
        "location": "Warehouse A",
        "temperature": 25.0,
        "humidity": 57,
        "storage_condition": "Store below 30C",
        "quality_status": "Passed",
    },
    {
        "medicine_code": "MED005",
        "name": "Omeprazole 20mg",
        "generic_name": "Omeprazole",
        "dosage_form": "Capsule",
        "strength": "20mg",
        "category": "Gastrointestinal",
        "manufacturer": "Pymepharco",
        "batch_number": "BATCH005",
        "manufacture_date": "2026-05-01",
        "expiration_date": "2028-05-01",
        "description": "Medicine for gastric acid control.",
        "location": "Warehouse D",
        "temperature": 24.5,
        "humidity": 56,
        "storage_condition": "Store in dry place, below 30C",
        "quality_status": "Passed",
    },
    {
        "medicine_code": "MED006",
        "name": "Loratadine 10mg",
        "generic_name": "Loratadine",
        "dosage_form": "Tablet",
        "strength": "10mg",
        "category": "Antihistamine",
        "manufacturer": "Traphaco",
        "batch_number": "BATCH006",
        "manufacture_date": "2026-01-20",
        "expiration_date": "2028-01-20",
        "description": "Medicine for allergy symptom relief.",
        "location": "Warehouse A",
        "temperature": 25.2,
        "humidity": 59,
        "storage_condition": "Store below 30C",
        "quality_status": "Passed",
    },
    {
        "medicine_code": "MED007",
        "name": "Metformin 500mg",
        "generic_name": "Metformin Hydrochloride",
        "dosage_form": "Tablet",
        "strength": "500mg",
        "category": "Antidiabetic",
        "manufacturer": "Domesco",
        "batch_number": "BATCH007",
        "manufacture_date": "2026-02-18",
        "expiration_date": "2028-02-18",
        "description": "Medicine for blood glucose control.",
        "location": "Warehouse B",
        "temperature": 24.8,
        "humidity": 57,
        "storage_condition": "Store below 30C",
        "quality_status": "Passed",
    },
    {
        "medicine_code": "MED008",
        "name": "Amlodipine 5mg",
        "generic_name": "Amlodipine",
        "dosage_form": "Tablet",
        "strength": "5mg",
        "category": "Cardiovascular",
        "manufacturer": "Stada Vietnam",
        "batch_number": "BATCH008",
        "manufacture_date": "2026-03-22",
        "expiration_date": "2028-03-22",
        "description": "Medicine for hypertension treatment.",
        "location": "Warehouse C",
        "temperature": 24.3,
        "humidity": 56,
        "storage_condition": "Store below 30C",
        "quality_status": "Passed",
    },
    {
        "medicine_code": "MED009",
        "name": "Losartan 50mg",
        "generic_name": "Losartan Potassium",
        "dosage_form": "Tablet",
        "strength": "50mg",
        "category": "Cardiovascular",
        "manufacturer": "Bidiphar",
        "batch_number": "BATCH009",
        "manufacture_date": "2026-04-05",
        "expiration_date": "2028-04-05",
        "description": "Medicine for hypertension treatment.",
        "location": "Warehouse C",
        "temperature": 24.7,
        "humidity": 55,
        "storage_condition": "Store in dry place",
        "quality_status": "Passed",
    },
    {
        "medicine_code": "MED010",
        "name": "Atorvastatin 20mg",
        "generic_name": "Atorvastatin Calcium",
        "dosage_form": "Tablet",
        "strength": "20mg",
        "category": "Cardiovascular",
        "manufacturer": "Pymepharco",
        "batch_number": "BATCH010",
        "manufacture_date": "2026-05-14",
        "expiration_date": "2028-05-14",
        "description": "Medicine for cholesterol control.",
        "location": "Warehouse D",
        "temperature": 25.1,
        "humidity": 58,
        "storage_condition": "Store below 30C",
        "quality_status": "Passed",
    },
    {
        "medicine_code": "MED011",
        "name": "Cefixime 200mg",
        "generic_name": "Cefixime",
        "dosage_form": "Capsule",
        "strength": "200mg",
        "category": "Antibiotic",
        "manufacturer": "Mekophar",
        "batch_number": "BATCH011",
        "manufacture_date": "2026-01-28",
        "expiration_date": "2028-01-28",
        "description": "Cephalosporin antibiotic.",
        "location": "Warehouse B",
        "temperature": 24.6,
        "humidity": 59,
        "storage_condition": "Store below 30C",
        "quality_status": "Passed",
    },
    {
        "medicine_code": "MED012",
        "name": "Azithromycin 500mg",
        "generic_name": "Azithromycin",
        "dosage_form": "Tablet",
        "strength": "500mg",
        "category": "Antibiotic",
        "manufacturer": "Imexpharm",
        "batch_number": "BATCH012",
        "manufacture_date": "2026-02-25",
        "expiration_date": "2028-02-25",
        "description": "Macrolide antibiotic.",
        "location": "Warehouse B",
        "temperature": 25.0,
        "humidity": 57,
        "storage_condition": "Store in dry place",
        "quality_status": "Passed",
    },
    {
        "medicine_code": "MED013",
        "name": "Ibuprofen 400mg",
        "generic_name": "Ibuprofen",
        "dosage_form": "Tablet",
        "strength": "400mg",
        "category": "Anti-inflammatory",
        "manufacturer": "DHG Pharma",
        "batch_number": "BATCH013",
        "manufacture_date": "2026-03-10",
        "expiration_date": "2028-03-10",
        "description": "Pain reliever and anti-inflammatory medicine.",
        "location": "Warehouse A",
        "temperature": 24.9,
        "humidity": 60,
        "storage_condition": "Store below 30C",
        "quality_status": "Passed",
    },
    {
        "medicine_code": "MED014",
        "name": "Diclofenac 50mg",
        "generic_name": "Diclofenac Sodium",
        "dosage_form": "Tablet",
        "strength": "50mg",
        "category": "Anti-inflammatory",
        "manufacturer": "Stella Pharm",
        "batch_number": "BATCH014",
        "manufacture_date": "2026-04-18",
        "expiration_date": "2028-04-18",
        "description": "Pain reliever and anti-inflammatory medicine.",
        "location": "Warehouse A",
        "temperature": 25.3,
        "humidity": 58,
        "storage_condition": "Store below 30C",
        "quality_status": "Passed",
    },
    {
        "medicine_code": "MED015",
        "name": "Salbutamol 2mg",
        "generic_name": "Salbutamol",
        "dosage_form": "Tablet",
        "strength": "2mg",
        "category": "Respiratory",
        "manufacturer": "Traphaco",
        "batch_number": "BATCH015",
        "manufacture_date": "2026-05-20",
        "expiration_date": "2028-05-20",
        "description": "Medicine for bronchospasm treatment support.",
        "location": "Warehouse D",
        "temperature": 24.4,
        "humidity": 56,
        "storage_condition": "Store below 30C",
        "quality_status": "Passed",
    },
    {
        "medicine_code": "MED016",
        "name": "Ambroxol 30mg",
        "generic_name": "Ambroxol Hydrochloride",
        "dosage_form": "Tablet",
        "strength": "30mg",
        "category": "Respiratory",
        "manufacturer": "OPC Pharma",
        "batch_number": "BATCH016",
        "manufacture_date": "2026-01-11",
        "expiration_date": "2028-01-11",
        "description": "Expectorant medicine.",
        "location": "Warehouse D",
        "temperature": 24.5,
        "humidity": 55,
        "storage_condition": "Keep in dry place",
        "quality_status": "Passed",
    },
    {
        "medicine_code": "MED017",
        "name": "Dextromethorphan 15mg",
        "generic_name": "Dextromethorphan",
        "dosage_form": "Syrup",
        "strength": "15mg/5ml",
        "category": "Respiratory",
        "manufacturer": "Mekophar",
        "batch_number": "BATCH017",
        "manufacture_date": "2026-02-07",
        "expiration_date": "2027-02-07",
        "description": "Cough relief medicine.",
        "location": "Warehouse D",
        "temperature": 23.8,
        "humidity": 57,
        "storage_condition": "Store below 25C",
        "quality_status": "Passed",
    },
    {
        "medicine_code": "MED018",
        "name": "ORS Sachet",
        "generic_name": "Oral Rehydration Salts",
        "dosage_form": "Powder",
        "strength": "Standard sachet",
        "category": "Electrolyte",
        "manufacturer": "Bidiphar",
        "batch_number": "BATCH018",
        "manufacture_date": "2026-03-17",
        "expiration_date": "2028-03-17",
        "description": "Oral rehydration salt powder.",
        "location": "Warehouse C",
        "temperature": 25.0,
        "humidity": 54,
        "storage_condition": "Keep away from moisture",
        "quality_status": "Passed",
    },
    {
        "medicine_code": "MED019",
        "name": "Ferrous Sulfate 200mg",
        "generic_name": "Ferrous Sulfate",
        "dosage_form": "Tablet",
        "strength": "200mg",
        "category": "Mineral Supplement",
        "manufacturer": "Domesco",
        "batch_number": "BATCH019",
        "manufacture_date": "2026-04-09",
        "expiration_date": "2028-04-09",
        "description": "Iron supplement medicine.",
        "location": "Warehouse C",
        "temperature": 24.2,
        "humidity": 56,
        "storage_condition": "Store in dry place",
        "quality_status": "Passed",
    },
    {
        "medicine_code": "MED020",
        "name": "Calcium D3",
        "generic_name": "Calcium Carbonate + Vitamin D3",
        "dosage_form": "Tablet",
        "strength": "Calcium 500mg + Vitamin D3",
        "category": "Mineral Supplement",
        "manufacturer": "OPC Pharma",
        "batch_number": "BATCH020",
        "manufacture_date": "2026-05-08",
        "expiration_date": "2028-05-08",
        "description": "Calcium and vitamin D3 supplement.",
        "location": "Warehouse C",
        "temperature": 24.9,
        "humidity": 55,
        "storage_condition": "Store below 30C",
        "quality_status": "Passed",
    },
]


class Command(BaseCommand):
    help = "Seed the 20 medicine batches provided by the team into MongoDB."

    def handle(self, *args, **options):
        repo = MedicineRepository()

        try:
            repo.create_indexes()
        except RuntimeError as exc:
            raise CommandError(
                "Cannot seed medicines because MongoDB is not available. "
                "Start MongoDB on localhost:27017 or update MONGO_URI."
            ) from exc

        created_count = 0
        skipped_count = 0
        for medicine in MEDICINES:
            if repo.find_by_batch_number(medicine["batch_number"]):
                skipped_count += 1
                continue

            payload = dict(medicine)
            payload.setdefault("status", DEFAULT_MEDICINE_STATUS)
            payload.setdefault("blockchain_hash", "")
            payload["timestamp"] = timezone.now()
            repo.create(payload)
            created_count += 1

        self.stdout.write(self.style.SUCCESS(
            f"Seed medicines completed: {created_count} created, {skipped_count} skipped."
        ))
